name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: sudo apt-get update -q && sudo apt-get install -yq --no-install-recommends luajit lua-check
      - uses: nebularg/actions-luacheck@v1
        with:
          args: --no-color -q
          annotate: warning
      - run: luajit test.lua
